# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_service.proto',
  package='model_grpc_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13model_service.proto\x12\x12model_grpc_service\"\x07\n\x05\x65mpty\"\xbc\x01\n\x05model\x12\x16\n\x0equalified_name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\rmajor_version\x18\x04 \x01(\x11\x12\x15\n\rminor_version\x18\x05 \x01(\x11\x12\x12\n\ninput_type\x18\x06 \x01(\t\x12\x13\n\x0boutput_type\x18\x07 \x01(\t\x12\x19\n\x11predict_operation\x18\x08 \x01(\t\"=\n\x10model_collection\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.model_grpc_service.model\"h\n\x10iris_model_input\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x02\"$\n\x11iris_model_output\x12\x0f\n\x07species\x18\x01 \x01(\t2\xc8\x01\n\x10ModelgRPCService\x12O\n\nget_models\x12\x19.model_grpc_service.empty\x1a$.model_grpc_service.model_collection\"\x00\x12\x63\n\x12iris_model_predict\x12$.model_grpc_service.iris_model_input\x1a%.model_grpc_service.iris_model_output\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='model_grpc_service.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=50,
)


_MODEL = _descriptor.Descriptor(
  name='model',
  full_name='model_grpc_service.model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qualified_name', full_name='model_grpc_service.model.qualified_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='model_grpc_service.model.display_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='model_grpc_service.model.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='major_version', full_name='model_grpc_service.model.major_version', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor_version', full_name='model_grpc_service.model.minor_version', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_type', full_name='model_grpc_service.model.input_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_type', full_name='model_grpc_service.model.output_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predict_operation', full_name='model_grpc_service.model.predict_operation', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=241,
)


_MODEL_COLLECTION = _descriptor.Descriptor(
  name='model_collection',
  full_name='model_grpc_service.model_collection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='model_grpc_service.model_collection.models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=304,
)


_IRIS_MODEL_INPUT = _descriptor.Descriptor(
  name='iris_model_input',
  full_name='model_grpc_service.iris_model_input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sepal_length', full_name='model_grpc_service.iris_model_input.sepal_length', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sepal_width', full_name='model_grpc_service.iris_model_input.sepal_width', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_length', full_name='model_grpc_service.iris_model_input.petal_length', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_width', full_name='model_grpc_service.iris_model_input.petal_width', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=410,
)


_IRIS_MODEL_OUTPUT = _descriptor.Descriptor(
  name='iris_model_output',
  full_name='model_grpc_service.iris_model_output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='species', full_name='model_grpc_service.iris_model_output.species', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=448,
)

_MODEL_COLLECTION.fields_by_name['models'].message_type = _MODEL
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['model'] = _MODEL
DESCRIPTOR.message_types_by_name['model_collection'] = _MODEL_COLLECTION
DESCRIPTOR.message_types_by_name['iris_model_input'] = _IRIS_MODEL_INPUT
DESCRIPTOR.message_types_by_name['iris_model_output'] = _IRIS_MODEL_OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.empty)
  })
_sym_db.RegisterMessage(empty)

model = _reflection.GeneratedProtocolMessageType('model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.model)
  })
_sym_db.RegisterMessage(model)

model_collection = _reflection.GeneratedProtocolMessageType('model_collection', (_message.Message,), {
  'DESCRIPTOR' : _MODEL_COLLECTION,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.model_collection)
  })
_sym_db.RegisterMessage(model_collection)

iris_model_input = _reflection.GeneratedProtocolMessageType('iris_model_input', (_message.Message,), {
  'DESCRIPTOR' : _IRIS_MODEL_INPUT,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.iris_model_input)
  })
_sym_db.RegisterMessage(iris_model_input)

iris_model_output = _reflection.GeneratedProtocolMessageType('iris_model_output', (_message.Message,), {
  'DESCRIPTOR' : _IRIS_MODEL_OUTPUT,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.iris_model_output)
  })
_sym_db.RegisterMessage(iris_model_output)



_MODELGRPCSERVICE = _descriptor.ServiceDescriptor(
  name='ModelgRPCService',
  full_name='model_grpc_service.ModelgRPCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=451,
  serialized_end=651,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_models',
    full_name='model_grpc_service.ModelgRPCService.get_models',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MODEL_COLLECTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='iris_model_predict',
    full_name='model_grpc_service.ModelgRPCService.iris_model_predict',
    index=1,
    containing_service=None,
    input_type=_IRIS_MODEL_INPUT,
    output_type=_IRIS_MODEL_OUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELGRPCSERVICE)

DESCRIPTOR.services_by_name['ModelgRPCService'] = _MODELGRPCSERVICE

# @@protoc_insertion_point(module_scope)
