# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_service.proto',
  package='model_grpc_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13model_service.proto\x12\x12model_grpc_service\"h\n\x10iris_model_input\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x02\"$\n\x11iris_model_output\x12\x0f\n\x07species\x18\x01 \x01(\t2w\n\x10ModelgRPCService\x12\x63\n\x12iris_model_predict\x12$.model_grpc_service.iris_model_input\x1a%.model_grpc_service.iris_model_output\"\x00\x62\x06proto3')
)




_IRIS_MODEL_INPUT = _descriptor.Descriptor(
  name='iris_model_input',
  full_name='model_grpc_service.iris_model_input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sepal_length', full_name='model_grpc_service.iris_model_input.sepal_length', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sepal_width', full_name='model_grpc_service.iris_model_input.sepal_width', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_length', full_name='model_grpc_service.iris_model_input.petal_length', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_width', full_name='model_grpc_service.iris_model_input.petal_width', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=147,
)


_IRIS_MODEL_OUTPUT = _descriptor.Descriptor(
  name='iris_model_output',
  full_name='model_grpc_service.iris_model_output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='species', full_name='model_grpc_service.iris_model_output.species', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['iris_model_input'] = _IRIS_MODEL_INPUT
DESCRIPTOR.message_types_by_name['iris_model_output'] = _IRIS_MODEL_OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

iris_model_input = _reflection.GeneratedProtocolMessageType('iris_model_input', (_message.Message,), {
  'DESCRIPTOR' : _IRIS_MODEL_INPUT,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.iris_model_input)
  })
_sym_db.RegisterMessage(iris_model_input)

iris_model_output = _reflection.GeneratedProtocolMessageType('iris_model_output', (_message.Message,), {
  'DESCRIPTOR' : _IRIS_MODEL_OUTPUT,
  '__module__' : 'model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.iris_model_output)
  })
_sym_db.RegisterMessage(iris_model_output)



_MODELGRPCSERVICE = _descriptor.ServiceDescriptor(
  name='ModelgRPCService',
  full_name='model_grpc_service.ModelgRPCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=187,
  serialized_end=306,
  methods=[
  _descriptor.MethodDescriptor(
    name='iris_model_predict',
    full_name='model_grpc_service.ModelgRPCService.iris_model_predict',
    index=0,
    containing_service=None,
    input_type=_IRIS_MODEL_INPUT,
    output_type=_IRIS_MODEL_OUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELGRPCSERVICE)

DESCRIPTOR.services_by_name['ModelgRPCService'] = _MODELGRPCSERVICE

# @@protoc_insertion_point(module_scope)
